fix: tokens

diff --git a/.github/actions/release/publish-draft-release/action.yml b/.github/actions/release/publish-draft-release/action.yml
--- a/.github/actions/release/publish-draft-release/action.yml
+++ b/.github/actions/release/publish-draft-release/action.yml
@@ -21,7 +21,7 @@ runs:
       run: |
         set -e
         tag="${{ inputs.tag }}"
-        release_response=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }} \
+        release_response=$(curl -s -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
           "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
 
         if echo "$release_response" | grep -q '"message": "Not Found"'; then
@@ -35,18 +35,21 @@ runs:
       shell: bash
 
     - name: Publish release
-      if: ${{ steps.check_release.outputs.release_exists == 'true' }}
       run: |
         set -e
-        release_id="${{ steps.check_release.outputs.release_id }}"
-        response=$(curl -s -X PATCH -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
-          -d '{"draft": false}' \
-          "https://api.github.com/repos/${{ github.repository }}/releases/$release_id")
-        echo "Response: $response"
-        if echo "$response" | jq -e '.id' >/dev/null; then
-          echo "Release updated successfully"
+        if [[ "${{ steps.check_release.outputs.release_exists }}" == "true" ]]; then
+          release_id="${{ steps.check_release.outputs.release_id }}"
+          response=$(curl -s -X PATCH -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
+            -d '{"draft": false}' \
+            "https://api.github.com/repos/${{ github.repository }}/releases/$release_id")
+          echo "Response: $response"
+          if echo "$response" | jq -e '.id' >/dev/null; then
+            echo "Release updated successfully"
+          else
+            echo "Failed to update release"
+            exit 1
+          fi
         else
-          echo "Failed to update release"
-          exit 1
+          echo "Release does not exist, skipping publish step."
         fi
       shell: bash
